### PR TITLE
Use LLVM.Typed from llvm-hs-pure

### PR DESCRIPTION
**Pull request by sdiehl**
Is dependent on the `llvm-hs-pure` library on Hackage exposing ``LLVM.Typed``.

### CODE REVIEW

**Comment by sdiehl** [comment]
When we cut the next version of `llvm-hs`` I'll cut a point release of this that points at the stable Hackage version and merge this.

**Comment by sdiehl** [comment]
The Hackage index appears to be out of sync with our latest package. I'll try again in 24 hours and see if this passes.

**Comment by cocreature** [comment]
After restarting the build it was now successful. Apparently Hackage broke when I uploaded the new version of `llvm-hs` https://github.com/haskell/hackage-server/issues/643#issuecomment-352207372

**Comment by sdiehl** [comment]
> Apparently Hackage broke when I uploaded the new version

:joy: That's reassuring.

**Pull request merged**
