### PR TITLE
Upgrade to 5.0

### PR DESCRIPTION
**Pull request by sdiehl**

### CODE REVIEW

**Comment by cocreature** [comment]
@sdiehl Is there anything specific that’s left to do before we merge this? The test failures don’t seem to be present with LLVM 4.0 as well so I wouldn’t see this as a blocker.

**Comment by sdiehl** [comment]
I can merge this, just wanted to isolate the work on the 5.0 compat and get all the tests passing before putting it on master. Some projects depend on it now so I'm a little wary about breakage.

**Comment by cocreature** [comment]
Great, I have fixes for about 2/3 of the failing tests lying around but I probably won’t get around to submitting PRs before next tuesday.

**Comment by sdiehl** [comment]
Yeah, no rush. Most of the open source LLVM projects haven't upgraded yet.

**Pull request merged**
