### PR TITLE
Migrating to  prettyprinter 1.2.0.1

### PR DESCRIPTION
**Pull request by yogeshsajanikar**
* Replacing old PP by Pretty
* Added functions pp<Context> wherever we require non-standard implementation for lists, tuples etc.
* All tests are passing.

### CODE REVIEW

**Comment by sdiehl** [comment]
@cocreature What are your thoughts on this? I was going to go through and fix the conflict but I think we can roll over to the new pretty printer with this PR.

**Comment by cocreature** [comment]
Great work @yogeshsajanikar, thanks a lot!

There are some commented-out instances that should probably just be removed but apart from that, this looks ready once the conflicts are fixed :+1:

**Comment by yogeshsajanikar** [comment]
@cocreature @sdiehl Can I merge with latest master, create a pull request. That should resolve the conflict as well. Plus I also removed 1 newtype's (which were added by me to get rid of default class instance).

**Comment by cocreature** [comment]
@yogeshsajanikar You can just update this PR, no need to create a new one. If you have trouble fixing the conflicts let me know and I’m happy to help!

**Comment by yogeshsajanikar** [comment]
@cocreature Updating pull request now.

**Comment by sdiehl** [comment]
I think this is good to merge, unless @cocreature has objections I'll merge it and upload the new major version.

**Comment by cocreature** [comment]
LGTM, great work @yogeshsajanikar!

**Pull request merged**
