### PR TITLE
Extensions to Pretty Printer

### PR DESCRIPTION
**Pull request by sdiehl**
Whenever you feel this is good to go upstream, just let me know. "Good enough" is probably fine. :+1:

### CODE REVIEW

**Comment by sdiehl** [comment]
@nomeata Would you like to just be made an owner of this project? You're working a lot faster than me and then you could just commit straight upstream.

**Comment by nomeata** [comment]
If you want me to commit directly, I can do that. But I would like to avoid taking responsibility in the long run, or having to deal with project managements (writing tests, doing releases, etc.) – right now, I am just scratching an itch of mine. Also note that this is literally my first encounter with LLVM…

**Comment by sdiehl** [comment]
Yeah, I'll do the grunt work of tests and Hackage. Just trying to optimize so we could have one repo instead of maintaining n-different forks.

**Comment by nomeata** [comment]
Great. I’ll just wildly commit stuff that works for me to the master branch until you stop me :-)

**Comment by sdiehl** [comment]
Cool! :smile: 

Ok, you have an invitation at https://github.com/llvm-hs .

**Comment by nomeata** [comment]
https://github.com/nomeata/veggies/commit/bab5ee890cefa17354abe3b9ae3bb5be5c8b39b1 :-)

**Pull request merged**
