### PR TITLE
Update for llvm-hs-(pure) 6.2

### PR DESCRIPTION
**Pull request by cocreature**
This is not yet finished (so hold off from merging this) but it’ll probably take me a few more days until I finish it so to avoid duplicated work I’m opening the PR now.

### CODE REVIEW

**Comment by sdiehl** [comment]
Looks great, adding the printer for all the debug information is a heroic task.

**Comment by sdiehl** [comment]
We'll cut a new major version when this is sorted.

**Comment by cocreature** [comment]
This depends on https://github.com/llvm-hs/llvm-hs/pull/205 but should otherwise be finished so once that is merged and `llvm-hs-(pure)-6.2.0` is released, we should be able to merge this.

**Comment by cocreature** [comment]
Alright, I’ve merged and released the fixes and restarted the travis build which now passes successfully.

**Comment by sdiehl** [comment]
Wonderful, thanks for fixing this. I'll sync up with up with Hackage.

**Pull request merged**
